/**
 * Homepage editorial content and view mappings (slices 02–03; alt text repaired
 * in REPAIR-09A).
 *
 * Page copy (hero, about preview) lives here. It is NOT duplicated source for
 * photography: the homepage route loads published photographs, featured work,
 * galleries and recent additions from the public query boundary
 * (`app/data/queries.ts`) and maps records to view objects with the helpers
 * below, so gallery names, covers and photo metadata come from the same source as
 * the public gallery and photo pages.
 *
 * REPAIR-09A: nothing here prefixes a real photograph's alternative text with
 * development wording. A record's own description is used unchanged, and the
 * visible "development preview" labels are gated by the single notice switch in
 * `app/data/site.ts`.
 */
import type {
  PublicGallery,
  PublicPhoto,
  PublicPhotoWithGallery,
} from "./model";
import { aspectRatioOf } from "./model";
import { galleryPath, photoPath } from "../lib/paths";

export const homepageMeta = {
  title: "Anyaparallax Photography — Night cities, live music, the moments after dark",
  /**
   * TRUE AT EVERY STAGE. The development wording is no longer part of this
   * sentence: it is appended by the route only while the development notices are
   * enabled, so a production page description cannot claim to be a preview.
   */
  description:
    "Street photography, live music and the energy of the night. The Anyaparallax photography portfolio.",
  /** Appended to {@link homepageMeta.description} when development notices are on. */
  previewSuffix: " Development preview.",
} as const;

export const hero = {
  headline: ["Cities", "People", "Music", "Moments"],
  supporting: "Street photography, live music and the energy of the night.",
  action: { label: "Explore galleries", to: "/galleries" },
  photo: {
    photo: "/images/dev/hero-night-boulevard.svg",
    /**
     * EMPTY, DELIBERATELY (REPAIR-09A). The hero is currently an abstract
     * development stand-in graphic generated by `scripts/generate-dev-images.mjs`
     * — blurred colour fields and grain, not a photograph of anything. The
     * alternative it replaces ("Development placeholder for the opening hero
     * photograph: a wet night boulevard…") is exactly the chrome this repair
     * removes, and inventing a scene description instead would assert something
     * false about an image that depicts no scene. An empty alternative marks the
     * stand-in for what it is: decorative, with nothing nameable to describe.
     * It is replaced when the operator supplies the approved hero photograph.
     */
    alt: "",
    ratio: "3 / 2",
  },
  /** Honest, visible label for the development stand-in used in the hero. Gated. */
  note: "Development preview — photography, copy and galleries are placeholders.",
} as const;

/** Short About preview. Final biography and wording await operator approval. */
export const aboutPreview = {
  title: "About Anya",
  body: "I'm Anya — a photographer drawn to the energy of cities, live music, cars and the moments that happen after dark. Anyaparallax is where that work gathers.",
  to: "/about",
  linkLabel: "More about Anya",
  photo: {
    photo: "/images/dev/street-portrait.svg",
    /**
     * EMPTY, DELIBERATELY (REPAIR-09A), for the same reason as the hero above: the
     * stand-in graphic depicts no portrait, so describing it as one — or as a
     * development placeholder — would be a claim the image cannot support.
     */
    alt: "",
    ratio: "4 / 5",
  },
} as const;

export type HomepagePhotoCard = {
  readonly id: string;
  readonly slug: string;
  /**
   * Browser-facing PUBLIC image path, or null when the stored reference could
   * not be converted. `src={card.photo}` is only rendered when it is a string.
   */
  readonly photo: string | null;
  readonly alt: string;
  readonly ratio: string;
  readonly title: string;
  readonly galleryTo: string;
  readonly galleryLabel: string;
  readonly to: string;
  /** Editorial grid slot for the featured presentation; presentation-only. */
  readonly variant: string;
};

export type HomepageGalleryCard = {
  readonly id: string;
  readonly name: string;
  readonly to: string;
  /** Cover image path (or null) and its alternative text. */
  readonly cover: { photo: string | null; alt: string } | null;
  readonly count: number;
  readonly description: string;
};

/**
 * The alternative text for a photograph, from the photograph's own public data.
 *
 * REPAIR-09A: this used to prefix every description with "Development
 * placeholder", so every photograph on the homepage was announced to assistive
 * technology as a placeholder before it said anything about the picture. The
 * rule is now the record's own words, unchanged: its description when it has one,
 * otherwise its title. Nothing is invented, and no development wording is
 * injected — a record that describes itself as development material (the seed set
 * does, deliberately) keeps its own description, which is the honest outcome.
 */
function photoAlt(photo: PublicPhoto): string {
  return photo.description || photo.title;
}

/** Public photograph with gallery context → homepage card view object. */
export function toPhotoCard(photo: PublicPhotoWithGallery): HomepagePhotoCard {
  return {
    id: photo.id,
    slug: photo.slug,
    // A PUBLIC path from the projection, never a storage key: `photo` is emitted
    // straight into an `src`. When the projection refused the stored reference
    // this is null, and the card renders without an image rather than with an
    // unloadable one.
    photo: photo.webImagePath,
    alt: photoAlt(photo),
    ratio: aspectRatioOf(photo),
    title: photo.title,
    galleryTo: galleryPath(photo.gallery.slug),
    galleryLabel: photo.gallery.name,
    to: photoPath(photo.slug),
    variant: photo.featuredVariant,
  };
}

/**
 * Published gallery → homepage collection card view object.
 *
 * The cover's alternative text is the cover PHOTOGRAPH's own words, exactly as
 * {@link photoAlt} derives them. REPAIR-09A removed the generated
 * "Development placeholder for the {gallery} cover photograph." string, which
 * described every collection cover on the site as a placeholder.
 */
export function toGalleryCard(
  gallery: PublicGallery,
  count: number,
  cover: PublicPhoto | null,
): HomepageGalleryCard {
  return {
    id: gallery.id,
    name: gallery.name,
    to: galleryPath(gallery.slug),
    cover: cover
      ? {
          photo: cover.thumbnailImagePath,
          alt: photoAlt(cover),
        }
      : null,
    count,
    description: gallery.description,
  };
}
