import type { MetaFunction } from "react-router";

import { site } from "../data/site";

export const meta: MetaFunction = () => [
  { title: `Privacy — ${site.name} ${site.secondary}` },
  {
    name: "description",
    content:
      "What this website stores when you send an enquiry or interact with a photograph, and what it deliberately does not collect.",
  },
];

/**
 * Privacy notice.
 *
 * WHY IT EXISTS: the site needed a Privacy destination before any anonymous launch, and a
 * footer link to nothing would be worse than no link at all.
 *
 * WHAT IT MAY AND MAY NOT SAY. Every statement below describes the ACTUAL code: the
 * enquiry rows and the columns they do not have, the anonymous per-browser identifier
 * used to count a like once, the absence of any IP/user-agent/referrer/fingerprint
 * storage, the absence of third-party analytics, and Cloudflare Access for operator
 * sign-in. Nothing here is a legal claim, and the three facts this application cannot know
 * — who the data controller is, how long enquiries are kept, and which address to write to
 * — are shown as an explicit operator task rather than invented.
 */
export default function PrivacyRoute() {
  return (
    <section className="page">
      <header className="page__header">
        <p className="eyebrow">Privacy</p>
        <h1>Privacy</h1>
        <p className="lede">
          What this site stores, why, and what it deliberately does not collect. Written to
          describe how the site actually works.
        </p>
      </header>

      <section className="workspace-block" aria-labelledby="operator-tasks-heading">
        <h2 id="operator-tasks-heading">To be completed before public launch</h2>
        <p className="notice notice--warning">
          Three facts are the site owner's to decide, so they are shown here rather than
          guessed: the identity of the data controller, the retention period for enquiries,
          and the contact address for data requests. Replace this block with those details.
        </p>
      </section>

      <section className="workspace-block" aria-labelledby="enquiries-heading">
        <h2 id="enquiries-heading">When you send an enquiry</h2>
        <p>
          The contact form and the print enquiry form ask for your name, your email address and
          your message, plus the category of enquiry and, for a print enquiry, the photograph
          and the format you are interested in. Those details are stored so the enquiry can be
          answered.
        </p>
        <p>
          The stored enquiry does not include your IP address, your browser or device details,
          the page you came from, or any identifier for your browser. The forms also carry a
          one-time submission token so that pressing send twice does not create two enquiries.
        </p>
        <p>
          Enquiries are read only in the site's private operator area, behind Cloudflare Access.
        </p>
      </section>

      <section className="workspace-block" aria-labelledby="engagement-heading">
        <h2 id="engagement-heading">Likes and shares</h2>
        <h3>The engagement cookie</h3>
        <p>
          To stop the same browser counting the same like twice, this site sets one first-party
          cookie called <code>anyaparallax_browser</code>. It holds a random value generated by
          this site. It is marked HttpOnly, so scripts on the page cannot read it; SameSite=Lax;
          and Secure when you are on an encrypted connection. It is sent only to this site, it
          lasts up to 400 days, and it is not used for anything else.
        </p>
        <p>
          The value is not derived from your IP address, your browser or device details, the page
          you came from, or anything you type, and it is not shared with anybody. The site's
          database never stores the cookie value itself: it stores a one-way SHA-256 digest of it,
          which is enough to recognise a repeat like and not enough to reconstruct the cookie.
          Clearing your cookies removes the identifier, and a new one is generated the next time
          you like a photograph.
        </p>
        <p>
          When you use a share control, this site records that a share action was started and
          which channel you chose. It cannot see whether the share completed, and it does not
          send anything to those services on your behalf.
        </p>
      </section>

      <section className="workspace-block" aria-labelledby="not-collected-heading">
        <h2 id="not-collected-heading">What this site does not do</h2>
        <ul className="plain-list">
          <li>No third-party analytics, advertising or tracking scripts.</li>
          <li>No IP address, user agent or referrer is stored with any visitor action.</li>
          <li>No fingerprinting, and no attempt to recognise a device across sites.</li>
          <li>No account is needed to browse, like or share.</li>
          <li>
            No analytics, advertising or profiling cookie is set, and no cookie is required to
            browse the site.
          </li>
        </ul>
      </section>

      <section className="workspace-block" aria-labelledby="operators-heading">
        <h2 id="operators-heading">Operator sign-in</h2>
        <p>
          The site's own management areas are protected by Cloudflare Access. Only the people
          the site owner has authorised can reach them, and this site never sees or stores their
          passwords. Visitors are unaffected by that arrangement.
        </p>
      </section>

      <section className="workspace-block" aria-labelledby="questions-heading">
        <h2 id="questions-heading">Questions or requests</h2>
        <p>
          To ask about an enquiry you have sent, or to ask for it to be corrected or removed,
          use the <a className="text-link" href="/contact">contact form</a> and say what you would
          like done. No public email address is published on this site.
        </p>
      </section>
    </section>
  );
}
